# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/root/.oh-my-zsh"


ZSH_THEME="robbyrussell"

plugins=(git extract)

source /root/.zinit/bin/zinit.zsh

alias c="clear"
alias ra="ranger"
alias s="neofetch"

source $ZSH/oh-my-zsh.sh
# source ~/.config/zsh/ln.zsh
source ~/.config/zsh/env.zsh
source /usr/local/python36/bin/virtualenvwrapper.sh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
# setting theme magicmace
# source ~/.config/zsh/magicmace.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
