export ZSH="/root/.oh-my-zsh"


# ZSH_THEME="robbyrussell"
ZSH_THEME="avit"

plugins=(git zsh-syntax-highlighting zsh-autosuggestions)


source $ZSH/oh-my-zsh.sh

source ~/.config/zsh/env.zsh
source /usr/local/python36/bin/virtualenvwrapper.sh

ln -s -f ~/.config/tmux/tmxu.conf ~/.tmux.conf
ln -s -f ~/.config/tmux/tmxu.conf.local ~/.tmux.conf.local

