export ZSH="/root/.oh-my-zsh"


# ZSH_THEME="robbyrussell"
ZSH_THEME="robbyrussell"


plugins=(git extract)


alias tmux="TERM=screen-256color-bce tmux"

source $ZSH/oh-my-zsh.sh
# source ~/.config/zsh/ln.zsh
source ~/.config/zsh/env.zsh
source /usr/local/python36/bin/virtualenvwrapper.sh
source ~/.config/zsh/plugins.zsh

source ~/.config/zsh/magicmace.zsh
